version: '2'
services:
    meineinitiative-app:
        image: meineinitiative
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://meineinitiative-mysql:3306/meineinitiative?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    meineinitiative-mysql:
        extends:
            file: mysql.yml
            service: meineinitiative-mysql
